"/":
  controller: Pages
  action: default

"/dashboard":
  controller: Pages
  action: dashboard

"/login":
  controller: Users
  action: login

"/save":
  controller: Users
  action: save

"/check":
  controller: Users
  action: checkCredentials

"/logout":
  controller: Users
  action: logout

"/register":
  controller: Users
  action: add

"/facebook_login":
  controller: Facebook
  action: loginFacebook

"/facebook_callback":
  controller: Facebook
  action: callbackFacebook

"/facebook_user":
  controller: Facebook
  action: getUsersInfo

"/heroku_login":
  controller: Heroku
  action: loginHeroku

"/heroku_callback":
  controller: Heroku
  action: callbackHeroku

"/heroku_user":
  controller: Heroku
  action: getUsersInfo

"/github__login":
  controller: Github
  action: loginGithub

"/github_callback":
  controller: Github
  action: callbackGithub

"/github__user":
  controller: Github
  action: getUsersInfo

