"/":
  controller: Pages
  action: default

"/dashboard":
  controller: Pages
  action: dashboard

"/login":
  controller: Users
  action: login

"/save":
  controller: Users
  action: save

"/check":
  controller: Users
  action: checkCredentials

"/logout":
  controller: Users
  action: logout

"/register":
  controller: Users
  action: add

"/OAuth_login":
  controller: Provider
  action: login

"/OAuth_callback":
  controller: Provider
  action: callback